### ISSUE TITLE
Error: Incorrect number of weight lines in the matrix input file

### ISSUE THREAD

**Issue by SaraValsoni** [VorontsovIE/sarus#4]
Hello,

I am using your tool on a given sequence to predict TF binding sites. With the mononucleotide matrices dowloaded from the Hocomoco website (v11) I got the results but when I try with the dinucleotide matrices it does not recognize them having the correct number of lines (even if I try with the --transpose parameter).
The command that I am using is like:

java -jar sarus-2.0.2.jar file.fasta ATF1_HUMAN.H11DI.0.B.dpwm 0.0005 --pvalues-file ATF1_HUMAN.H11DI.0.B.thr --output-scoring-mode pvalue --output-bed --threshold-mode pvalue

Is there any mistake or did I have to put a specific parameter for dinucleotide matrices?

Sara

**Comment by VorontsovIE** [comment]
Hello, Sara
With dinucleotide motifs you should invoke a dinucleotide version of the tool (`ru.autosome.di.SARUS` class in the same jar file). Your command will be the following:
`java -cp sarus-2.0.2.jar ru.autosome.di.SARUS file.fasta ATF1_HUMAN.H11DI.0.B.dpwm 0.0005 --pvalues-file ATF1_HUMAN.H11DI.0.B.thr --output-scoring-mode pvalue --output-bed --threshold-mode pvalue`

**Comment by SaraValsoni** [comment]
Thank you!
